// Pipeline: crawl → dedup → index → facts → retrieve → answer → eval.
// This is the very first step of the crawl: it turns one sitemap URL into the list of pages the
// crawler will then fetch. Its failure mode is invisible — a <url> silently dropped here is a
// document that never enters the corpus, is never chunked and can never be cited, and nobody
// downstream can tell the difference between "the page does not exist" and "we lost it".
//
// Parsed with regexes instead of an XML parser on purpose: these files are machine-generated by
// the CMS (one flat <urlset>, no CDATA, no namespace tricks we care about), so a parser
// dependency would buy nothing. If a hand-written sitemap ever shows up, this is the first place
// to suspect.

import { politeFetch } from "./fetch.js";

export interface SitemapEntry {
  url: string;
  /** The sitemap's own <lastmod>. NOT a publication date — see readSitemap. */
  lastmod: string | null;
  /** Which sitemap this URL came from; kept so provenance stays answerable after the merge. */
  sitemap: string;
}

/**
 * How many nested <sitemapindex> levels are followed. An index may list further indexes, and a
 * self-referencing (or mutually-referencing) index would otherwise recurse forever. Three levels
 * — index → per-section index → urlset — covers every layout in this corpus.
 */
const MAX_INDEX_DEPTH = 2;

// <sitemap><loc>https://everstake.com/sitemap-posts.xml</loc><lastmod>2026-01-01</lastmod></sitemap>
// The lazy [\s\S]*? skips whatever other children the block has, in any order; [^<\s]+ is the URL.
const CHILD_SITEMAP_RE = /<sitemap>[\s\S]*?<loc>\s*([^<\s]+)\s*<\/loc>[\s\S]*?<\/sitemap>/gi;
// <url><loc>https://everstake.com/resources/blog/post</loc><lastmod>2026-05-05</lastmod></url>
const URL_BLOCK_RE = /<url>([\s\S]*?)<\/url>/gi;
// <loc>  https://everstake.com/a  </loc> → "https://everstake.com/a" (sitemaps are pretty-printed)
const LOC_RE = /<loc>\s*([^<\s]+)\s*<\/loc>/i;
// <lastmod>2026-05-05</lastmod>, or the full <lastmod>2026-05-05T10:00:00+00:00</lastmod> form
const LASTMOD_RE = /<lastmod>\s*([^<\s]+)\s*<\/lastmod>/i;

/**
 * Read a sitemap (or a sitemap index, recursively) into a flat list of page URLs.
 *
 * `lastmod` is carried through but is deliberately never used as a publication date: the
 * everstake.com domain migration re-stamped 156 old posts with a 2026 lastmod (REPORT §2.2), so
 * it records the last CMS edit, not when the page was written. The crawler uses it only to rank
 * blog posts by recency when trimming to `crawl.max_blog_posts`.
 *
 * `depth` is internal — callers pass a single URL and get every page underneath it.
 */
export async function readSitemap(sitemapUrl: string, depth = 0): Promise<SitemapEntry[]> {
  if (depth > MAX_INDEX_DEPTH) return [];
  const response = await politeFetch(sitemapUrl);
  // A 403/404/timeout on one sitemap must not abort the crawl: the other sources still produce a
  // corpus, and the missing source shows up as a low document count for that source in the report.
  if (!response.ok) {
    console.warn(`  sitemap ${sitemapUrl} → ${response.error}`);
    return [];
  }
  if (/<sitemapindex/i.test(response.body)) return readChildSitemaps(response.body, depth);
  return parseUrlEntries(response.body, sitemapUrl);
}

/**
 * Follow every child listed in a sitemap index. Children are read one at a time (politeFetch
 * serialises per host anyway) and a child that fails contributes nothing, so a single broken
 * child sitemap cannot take its healthy siblings' URLs down with it.
 */
async function readChildSitemaps(indexXml: string, depth: number): Promise<SitemapEntry[]> {
  const entries: SitemapEntry[] = [];
  for (const childSitemap of indexXml.matchAll(CHILD_SITEMAP_RE)) {
    entries.push(...(await readSitemap(childSitemap[1].trim(), depth + 1)));
  }
  return entries;
}

/**
 * Turn a <urlset> into entries. Note that only the <lastmod> found *inside a <url> block* is
 * read: an index's own <lastmod> describes the child sitemap file, not any page, and attributing
 * it to a page would hand ranking a fabricated date.
 */
function parseUrlEntries(urlsetXml: string, sitemapUrl: string): SitemapEntry[] {
  const entries: SitemapEntry[] = [];
  for (const urlBlock of urlsetXml.matchAll(URL_BLOCK_RE)) {
    const location = urlBlock[1].match(LOC_RE)?.[1];
    if (!location) continue; // a <url> with no <loc> is malformed; an empty URL would be fetched as ""
    const lastmod = urlBlock[1].match(LASTMOD_RE)?.[1] ?? null;
    entries.push({ url: decodeXmlEntities(location.trim()), lastmod, sitemap: sitemapUrl });
  }
  return entries;
}

/**
 * The five predefined XML entities. `&amp;` is the one that actually matters: a <loc> escapes the
 * separators in `?a=1&amp;b=2`, and fetching that literally would request a different URL than
 * the site advertised.
 */
function decodeXmlEntities(value: string): string {
  return value
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'");
}
