import { existsSync } from "node:fs";
import { loadEnvFile } from "node:process";
import { serve } from "@hono/node-server";
import { openDatabase } from "./storage/database.js";
import { createApplication } from "./application.js";
import { createApi } from "./api.js";
if (existsSync(".env")) loadEnvFile();
const db = openDatabase();
const app = createApi(createApplication(db));
const port = Number(process.env.PORT ?? 4318);
serve({ fetch: app.fetch, port });
console.log(`Everstate Knowledge Base listening on ${port}`);
